In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
#Task 1
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Task 2
first_array = np.array([1,2,3,4,5])
second_array = np.array([6,7,8,9,10])
sum_arrays = first_array+second_array
sum_arrays

array([ 7,  9, 11, 13, 15])

In [12]:
#Task 3
new_array = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(new_array)):
    if new_array[i] % 2 == 0:
        print(new_array[i])

2
4
6
8
10


In [13]:
#Task 3 alternative
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1::2])

[ 2  4  6  8 10]
